---
title: "AllelicImbalance Vignette"
author: "Jesper R. Gådin and Lasse Folkersen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

This AllelicImbalance package contains functions for investigating
allelic imbalance effects in RNA-seq data. Maternal and paternal
alleles could be expected to show identical transcription rate, resulting in a
50%-50% mix of maternal and paternal mRNA in a sample. However, this turns out
to sometimes not be the case. The most extreme example is the X-chromosome
inactivation in females, but many autosomal genes also have deviations from
identical transcription rate. The causes of this are not always known, but one
likely cause is the difference in DNA, namely heterozygous SNPs, affecting
enhancers, promoter regions, splicing and stability. Identifying this allelic
imbalance is therefore of interest to the characterization of the genome and the
aim of the AllelicImbalance package is to facilitate this.

## Simple example of building an ASEset object
In this section we will walk through the various ways an ASEset
object can be created. The ASEset object has the SummarizedExperiment as parent class, and all functions you can apply on this class you can also apply on an ASEset. Although the preprocessing of RNA-seq data is not the
primary focus of this package, it is a necessary step before analysis. There
exists several different methods for obtaining a bam file, and this section
should just be considered an example. For further details we refer
to the web-pages of tophat, bowtie, bwa and samtools found in the links section at the end of this document.

```
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR009/ERR009135/*
bowtie -q --best --threads 5 --sam hg19 +
>      -1 ERR009135_1.fastq.gz -2 ERR009135_2.fastq.gz "ERR009135.sam"
samtools view -S -b ERR009135.sam > ERR009135.bam
```

In the above code one paired-end RNA sequencing sample is downloaded and
aligned to the human genome, then converted to bam using samtools. The
resulting bam files can be the direct input to the AllelicImbalance package. Other
aligners can be used as well, as long as bam files are provided as input. The
example code following illustrates how to use the import mechanism on a
chromosome 17-located subset of 20 RNA-seq experiments of HapMap samples. The
output is an \Robject{ASEset} object containing allele counts for all
heterozygote coding SNPs in the region.

```{r echo=TRUE, eval=FALSE}
searchArea <- GRanges(seqnames = c("17"), ranges = IRanges(79478301, 79478361))
pathToFiles <- system.file("extdata/ERP000101_subset", package = "AllelicImbalance")
reads <- impBamGAL(pathToFiles, searchArea, verbose = FALSE)
heterozygotePositions <- scanForHeterozygotes(reads, verbose = FALSE)
countList <- getAlleleCounts(reads, heterozygotePositions, verbose = FALSE)
a.simple <- ASEsetFromCountList(heterozygotePositions, countList)
a.simple
```

## Building an ASEset object using Bcf files
If more than a few genes and a few samples are analyzed we recommend
that a SNP-call is instead made using the samtools mpileup function (see
links section). The \Rfunction{scanForHeterozygotes} function is merely a simple 
SNP-caller and it is not as computationally optimized as mpileup. In this bash
code we download reference sequence for chromosome 17 and show how to generate
mpileup calls on one of the HapMap samples that were described above.

```
wget ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes/chr17.fa.gz
samtools mpileup -uf hg19.fa ERR009135.bam | bcftools view -bvcg - > ERR009135.bcf
```

Samtools mpileup generates by default a Vcf file which contains SNP and short INDEL 
positions. Piping the output to bcftools we get its binary equivalent (Bcf), which 
takes less space and can be queried more effective. With the Bcf files the process 
of generating an ASEset object starts with a call to the \Robject{impBcfGR} 
function instead. This function will import the Bcf file containing all SNP calls 
that were generated with the samtools mpileup function.


> "Who is is the master if nature provides the techniques to study itself"
